// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var ChainReactionMain$ReactTemplate = require("./app/components/ChainReactionMain.bs.js");

ReactDOMRe.renderToElementWithId(ReasonReact.element(/* None */0, /* None */0, ChainReactionMain$ReactTemplate.make(/* array */[])), "index1");

/*  Not a pure module */
